name: Test Setup PHP action

on:
  push

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Setup PHP
      uses: dino182/setup-php@1a2cb4f8725637734d73f54ddd402d23308a4959
      with:
        php-version: '7.4'
        extensions: fileinfo, gd
        tools: composer
      env:
        fail-fast: true
